- src/al.py
Implemented Query by committee.
Closes #33
> feat: query by committee

- src/transformer.py
> feat: load valence and arousal labels

- src/ml.py
- src/transformer.py
Implemented linear regression.
Closes #20
> feat: linear regression

- src/ml.py
Implementation of KNeighborsRegressor with multi-output.
Closes #21
> feat: kneighbors regressor

- .vscode/extensions.json
- .vscode/settings.json
> env: docstring formatter

- .gitignore
- requirements.txt
- src/feature_extraction.py
note:
* uses songs_info.csv as format for metadata
* only tested on emo-music
* data located locally in a folder called data* data located locally in a folder called data in root in root
csv data should be in:
LiU-AI-Project-Active-Learning-for-Music\data\emo-music-features\annotations
songs should be in:
LiU-AI-Project-Active-Learning-for-Music\data\emo-music-features\clips_45sec\clips_45seconds
new issue created #46 
Closes #41
> feat: feature extraction

- src/gui.py
- src/main.py
- src/windows.py
> Gui system and prompt for querying prior

- src/storage.py
- src/transformer.py
Data storage.
Closes #50 
Closes #19 
Closes #2
> feat: data storage

- src/feature_selection.py
Split into traning data and test data. And saves output as .npy
Saves output files in data-folder. 
Closes #46 #26
> Feature selection via PCA and Variance Threshold

- src/audio.py
- src/gui.py
- src/main.py
- src/windows.py
Note that the function mentioned in #22 is implicitly integrated into the solution. Also, in order to implement the dynamic querying, several other features had to be implemented before the window itself (see commits).
Closes #18 
Closes #22
> Gui dynamic

- src/feature_selection.py
- src/storage.py
- src/transformer.py
- Added default method that  only splits data in feature selection
- Created function for removing songs with high standard deviation in transformer
- NOTE: Updated docstrings for storage and transformer
Closes #15
> Data cleanup

- src/ml.py
- src/storage.py
- src/transformer.py
See commit msgs
Implemented tree regression
Also did:
refactors in ML
bugfixes in storage and transformer
Implemented new functions for accessing labels
Closes #23 
Closes #67
> Tree regression

- src/ml.py
note:
*fix docstrings to all ml-models
Closes #30
> feat: gradient boosted trees, votingregressor

- src/al.py
- src/feature_selection.py
fixed AL to return song_ids instead of index to samples. So it now works on a song basis instead of sample basis. Also added updated docstrings.
fixed pca such that the data is scaled correctly after PCA transformation.
Closes #75 
Closes #74
> Al fix and pca fix

- src/al.py
- src/ml.py
Note that the private field `storage.Dataset._contained_song_ids` is being accessed at the moment. This field should be exposed in some way, so that it may be accessed properly.
also:
* hyper parameter support for ml functions
Closes #76
> feat: ml and al input/output generalization

- src/storage.py
- src/transformer.py
Implemented sliding window functions in the storage class.
Closes #72
> feat: sliding window

- src/ml.py
Implemented neural network using MLPRegressor from sklearn.
Closes #25
> feat: neural network

- src/api/storage.py
- src/api/windows.py
Created an "add_songs" function in storage.py, that adds annotations to a dataset.
No need for parser.py
Closes #35 
Closes #80
> feat: annotation parser

- requirements.txt
- src/evaluation_phase.py
- src/phase_utils.py
- src/presentation_phase.py
- src/viability_phase.py
> Evaluation, Presentation phase

- src/evaluation_phase.py
- src/presentation_phase.py
> fix: plot best 'nr_models' mistake in presentation phase

- src/evaluation_phase.py
- src/learning_profile.py
> fix: support for hyper parameters

- src/init_phase.py
Support for running viability phase with 96 different Learning Profiles.
Closes #60
> feat: init phase with hyperparameters

- src/init_phase.py
- src/viability_phase.py
fix: uses validation data instead of test data
obs: must have newly formed datasets, see drive
> fix: uses validation data instead of test data

- src/viability_phase.py
> feat: multi-threading for viability phase

- src/api/storage.py
- src/api/transformer.py
- src/init_phase.py
> feat: init phase with sliding-window datasets

- src/evaluation_phase.py
- src/phase_utils.py
- src/presentation_phase.py
See git commit messages to see what is done. 
Closes #104
Closes #103 
Closes #102
> Utiliy phase functions and cleanup/refactoring

- src/phase_utils.py
Annotation class for saving annotations made by gui in a json file. 
Closes #82
> feat: annotation dictionary

- src/api/storage.py
- src/init_phase.py
- src/phase_utils.py
- src/user_phase.py
- src/viability_phase.py
> User phase

- src/learning_profile.py
- src/processes.py
> fix: print names instead of hash
